server:
  port: 8080
  servlet:
    context-path: /employee_management
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/employee_management"
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true